
ifeq ($(CONFIG_SPL_BUILD),y)
extra-y	= start.o
endif

obj-y += spl.o
obj-y += reset.o
obj-y += cpu.o
obj-y += clocks.o
obj-y += lowlevel_init_early.o
obj-y += lowlevel_init.o
obj-y += cps.o
obj-y += multi_core_boot.o
obj-y += serial.o
obj-y += dev_init.o
obj-y += gpio.o

obj-y += dramc/
